config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :rooms do
    resources :reservations, only: [:create]
    collection do
      get :search
    end
  end
  get 'manage-room/:id/photos' => 'rooms#photos', as: 'manage_room_photos'
  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :images, as: :imageable
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  has_many :reservations

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
      @photo = Photo.new(photo_params)
      if @photo.save
          render json: { message: "success", photoId: @photo.id }, status: 200
      else
          render json: { error: @photo.errors.full_messages.join(", ") }, status: 400
      end
  end

  def destroy
      @photo = Photo.find(params[:id])
      if @photo.destroy
          render json: { message: "file deleted from server" }
      else
          render json: { message: @photo.errors.full_messages.join(", ") }
      end
  end

  def list
      room = Room.find(params[:room_id])

      photos = []
      Photo.where(room_id: room.id).each do |photo|
          new_photo = {
              id: photo.id,
              name: photo.image_file_name,
              size: photo.image_file_size,
              src: photo.image(:thumb)
          }
          photos.push(new_photo)
      end
      render json: { images: photos }
  end

  private
  def photo_params
    params.require(:photo).permit(:image,:room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @rooms = Room.all
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to root_path, notice: "リスティングを作成・保存をしました"
    else
      redirect_to new_room_path, notice: "リスティングを作成・保存出来ませんでした"
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to root_path, notice: "リスティングを編集しました"
    else
      redirect_to new_room_path, notice: "リスティングを作成・保存出来ませんでした"
    end
  end

  def photos
    @room = Room.find(params[:id])
    @photo = Photo.new
  end

  def search
    @latitude = params[:lat]
    @longitude = params[:lng]
  end

  private
  def room_params
    params.require(:room).permit(:name, :detail, :image, :price, :room_type, :capacity, :bedroom_num, :bed_num, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def become_a_host
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def controller?(controller)
    controller.include?(params[:controller])#引数が現在のコントローラーに含まれていたらtrueを返す
  end

  def action?(action)
    action.include?(params[:action])#引数が現在のアクションに含まれていたらtrueを返す
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Airbnb
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'http://cdn.jsdelivr.net/momentjs/latest/moment.min.js'
    = stylesheet_link_tag 'http://cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css'
    = javascript_include_tag 'http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js'
    = stylesheet_link_tag 'http://cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.6.0/bootstrap-slider.min.js'
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.6.0/css/bootstrap-slider.min.css'
    = favicon_link_tag
    = csrf_meta_tags

  %body
    = yield

app/views/rooms/_card_swipe.html.haml
.slide-container
  .slide-content#slide-1
    .slide-1-container
      .h1 暮らす人と旅しよう
      .h4 お家、体験、スポット、すべてを1つのアプリで。
  .slide-content#slide-2
    #slide-2-img
      .slide-2-container
        .h1 Airbnbの体験
        .h4
          寿司職人、無敵のサーファーに（気分だけでも）
          %br
          変身しよう。
  .slide-content#slide-3
    .slide-3-content
      #slide-3-img
        .slide-3-container
          .slide-3-text
            .h1 Airbnbのスポット
            .h4 Woodyみたいなエキスパートと町を彷徨う。
  .slide-content#slide-4
    #slide-4-img
      .slide-4-container
        .h1
          LA会場から
          %br
          生中継
        .h4
          ブライアン・チェスキーCEOただいま登壇中。
          %br
          新たな「旅」の幕開けをお見逃しなく！

app/views/rooms/_edit_nav_bar.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{:class => "#{'active' if controller?("rooms") && action?("edit")}"}
    = link_to "基本情報", edit_room_path(@room)
  %li{:class => "#{'active' if controller?("rooms") && action?("photos")}"}
    = link_to "写真", manage_room_photos_path(@room), data:{no_turbolink: true}

app/views/rooms/_footer.html.haml
%hr
%footer.clearfix
  .container-fluid.page-1080px
    .row
      .col-md-2.language-curr-picker
        .col-sm-6.col-md-12.margin-bottom-8px
          %select#language-selector.form-control.bfh-languages
            %option{:value => "id"} Bahasa Indonesia
            %option{:value => "ms"} Bahasa Melayu
            %option{:value => "ca"} Català
            %option{:value => "da"} Dansk
            %option{:value => "de"} Deutsch
            %option{:value => "en"} English
            %option{:value => "es"} Español
            %option{:value => "el"} Eλληνικά
            %option{:value => "fr"} Français
            %option{:value => "it"} Italiano
            %option{:value => "hu"} Magyar
            %option{:value => "nl"} Nederlands
            %option{:value => "no"} Norsk
            %option{:value => "pl"} Polski
            %option{:value => "pt"} Português
            %option{:value => "fi"} Suomi
            %option{:value => "sv"} Svenska
            %option{:value => "tr"} Türkçe
            %option{:value => "is"} Íslenska
            %option{:value => "cs"} Čeština
            %option{:value => "ru"} Русский
            %option{:value => "th"} ภาษาไทย
            %option{:value => "zh"} 中文 (简体)
            %option{:value => "zh-TW"} 中文 (繁體)
            %option{:value => "ja", :selected => "selected"} 日本語
            %option{:value => "ko"} 한국어
          -# %label{for: "language-selector"}
        .col-sm-6.col-md-12
          %select.form-control.bfh-currencies{"data-currency" => "EUR"}
            %option{:value => "AED"} AED
            %option{:value => "ARS"} ARS
            %option{:value => "AUD"} AUD
            %option{:value => "BGN"} BGN
            %option{:value => "BRL"} BRL
            %option{:value => "CAD"} CAD
            %option{:value => "CHF"} CHF
            %option{:value => "CLP"} CLP
            %option{:value => "CNY"} CNY
            %option{:value => "COP"} COP
            %option{:value => "CRC"} CRC
            %option{:value => "CZK"} CZK
            %option{:value => "DKK"} DKK
            %option{:value => "EUR"} EUR
            %option{:value => "GBP"} GBP
            %option{:value => "HKD"} HKD
            %option{:value => "HRK"} HRK
            %option{:value => "HUF"} HUF
            %option{:value => "IDR"} IDR
            %option{:value => "ILS"} ILS
            %option{:value => "INR"} INR
            %option{:value => "JPY", :selected => "selected"} JPY
            %option{:value => "KRW"} KRW
            %option{:value => "MAD"} MAD
            %option{:value => "MXN"} MXN
            %option{:value => "MYR"} MYR
            %option{:value => "NOK"} NOK
            %option{:value => "NZD"} NZD
            %option{:value => "PEN"} PEN
            %option{:value => "PHP"} PHP
            %option{:value => "PLN"} PLN
            %option{:value => "RON"} RON
            %option{:value => "RUB"} RUB
            %option{:value => "SAR"} SAR
            %option{:value => "SEK"} SEK
            %option{:value => "SGD"} SGD
            %option{:value => "THB"} THB
            %option{:value => "TRY"} TRY
            %option{:value => "TWD"} TWD
            %option{:value => "UAH"} UAH
            %option{:value => "USD"} USD
            %option{:value => "UYU"} UYU
            %option{:value => "VND"} VND
            %option{:value => "ZAR"} ZAR

      .col-md-2.col-md-offset-1.hide-sm
        %h5 Airbnb
        %ul.list-layout
          %li
            %a Airbnbとは
          %li
            %a 採用情報
          %li
            %a プレス
          %li
            %a ポリシー
          %li
            %a ヘルプ
      .col-md-2.col-md-offset-1.hide-sm
        %h5 スタッフのおすすめ
        %ul.list-layout
          %li
            %a 信頼&安全
          %li
            %a お友達紹介クーポン
          %li
            %a Airbnb Citizen
          %li
            %a 出張
          %li
            %a ガイドブック
      .col-md-2.col-md-offset-1.hide-sm
        %h5 ホスティング
        %ul.list-layout
          %li
            %a ホストになる理由
          %li
            %a おもてなしの心
          %li
            %a ホストの責任
    %hr.space-top-8
    .pull-left
      %i.fa.fa-copyright.fa-1x
      %span Airbnb, Inc.
    .pull-right.padding-8
      %i.fa.fa-instagram.fa-1x
    .pull-right.padding-8
      %i.fa.fa-twitter.fa-1x
    .pull-right.padding-8
      %i.fa.fa-facebook.fa-1x
    .pull-right.padding-8
      %span サイトマップ
    .pull-right.padding-8
      %span 利用規約とプライバシー

app/views/rooms/_header.html.haml
.header.clearfix
  .pull-left
    = link_to "/" do
      .icon_box
        = image_tag '/images/favicon.ico.png', class: 'img-responsive'

  - if current_user
    .pull-right.height_100
      = link_to destroy_user_session_path, method: :delete, class: "header_link_container" do
        .header_content
          %span ログアウト
  - else
    .pull-right.height_100
      .header_content.header_link_container
        %button.btn.btn-default.user-avator{"data-target": "#modal_login", "data-toggle": "modal", type: "button"} ログイン
  - unless current_user
    .pull-right
      .header_content.header_link_container
        %button.btn.btn-default.user-avator{"data-target": "#modal_signup", "data-toggle": "modal", type: "button"} アカウント作成
  .pull-right
    =link_to "/signup_login", class: "header_link_container" do
      .header_content
        %span ヘルプ
  - if user_signed_in?
    .pull-right
      =link_to new_room_path, class: "header_link_container" do
        .header_content
          %span ホストになる
  - else
    .pull-right
      .header_content.header_link_container
        %button.btn.btn-default.user-avator{"data-target": "#modal_signup", "data-toggle": "modal", type: "button"} ホストになる


/ Modal login
#modal_login.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title.text-center ログインして下さい
      .modal-body
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          .form-group
            .field
              = f.label :email
              %br/
              = f.email_field :email, autofocus: true, class: 'form-control'
            .field
              = f.label :password
              %br/
              = f.password_field :password, autocomplete: "off", class: 'form-control'
            - if devise_mapping.rememberable?
              .field
                = f.check_box :remember_me
                = f.label :remember_me
                = f.submit value: 'ログイン', class: 'btn btn-block btn-danger btn-lg'

        = render "devise/shared/links"
        %span アカウントをお持ちではないですか？
        %button.btn.btn-default.user-avator{"data-target": "#modal_signup", "data-toggle": "modal", type: "button", class: 'btn btn-danger'}  ユーザー登録


/ Modal signup
#modal_signup.modal.fade{"aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title.text-center ユーザー登録してください
      .modal-body
        = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          = devise_error_messages!
          .form-group
            .field
              = f.label :name
              %br/
              = f.text_field :name, autofocus: true, class: 'form-control'
            .field
              = f.label :email
              %br/
              = f.email_field :email, class: 'form-control'
            .field
              = f.label :password
              - if @minimum_password_length
                %em
                  (#{@minimum_password_length} characters minimum)
              %br/
              = f.password_field :password, autocomplete: "off", class: 'form-control'
            .field
              = f.label :password_confirmation
              %br/
              = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'
              %h1
              = f.submit "登録", class: 'btn btn-block btn-danger btn-lg'

        = render "devise/shared/links"

app/views/rooms/_search_form.html.haml
.search-form
  = form_tag search_rooms_path, method: :get do
    .input-wrapper
      .search-form-location
        = hidden_field_tag :lat
        = hidden_field_tag :lng
        %label.search-form-label{for: 'search-location'}
          %span 場所
        %input#search-location{name: 'location',placeholder: '行き先、都市、住所', class: 'form-control'}
      .search-form-dates
        .container-fluid
          %label.search-form-label{for: 'start-date'}
            %span 日時
          .row
            .col-sm-5.input-date
              .date-range-picker
                %input{type: 'text', name: 'startDate', id: 'start-date', placeholder: 'チェックイン', class: 'input-date form-control'}
            .col-sm-1.text-center
              %p#date-arrow →
            .col-sm-5.input-date
              %input{type: 'text', name: 'endDate', id: 'end-date', placeholder: 'チェックアウト', class: 'input-date form-control'}
              .date-input.date-end
                -# %button
      .search-form-guests
        %label.search-form-label{for: 'how-many-guests'}
          %span ゲスト
        .guest-picker-trigger
          %select.form-control
            %option{:value => "1"} 宿泊1人
            %option{:value => "2"} 宿泊2人
            %option{:value => "3"} 宿泊3人
            %option{:value => "4"} 宿泊4人
            %option{:value => "5"} 宿泊5人
            %option{:value => "6人以上"} 宿泊6人以上
      .search-form-submit
        = submit_tag "探す", class: "btn btn-danger"

:javascript
  function init() {
  
    var input = /** @type {!HTMLInputElement} */(
        document.getElementById('search-location'));
  
  
    var autocomplete = new google.maps.places.Autocomplete(input);
  
    autocomplete.addListener('place_changed', function() {
      var place = autocomplete.getPlace();
      var lat = place.geometry.location.lat();
      var lng = place.geometry.location.lng();

      document.getElementById('lat').value = lat ;
      document.getElementById('lng').value = lng ;

      if (!place.geometry) {
        window.alert("Autocomplete's returned place contains no geometry");
        return;
      }
  
      var address = '';
      if (place.address_components) {
        address = [
          (place.address_components[0] && place.address_components[0].short_name || ''),
          (place.address_components[1] && place.address_components[1].short_name || ''),
          (place.address_components[2] && place.address_components[2].short_name || '')
        ].join(' ');
      }
  
    });
  
  }

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAXbvOKObMqITgrrvsCSne77MDEA3T9f8o&libraries=places&callback=init"}

app/views/rooms/_text_header.html.haml
.text-header-container
  %h1.text-header
    %span.text-airbnb
      %span Airbnb
      %span
    %span 世界に一つの家をブッキング。住民気分で街体験。

app/views/rooms/edit.html.haml
= render 'rooms/header'

.container-fluid
  .hosting-main-content.row
    .col-md-4
      = render 'rooms/edit_nav_bar'
    .col-md-8
      .landing__left-col-content
        .space-5
      .landing__step-content
        .h3
          %span お部屋の詳細を編集して下さい
        .container-fluid
          = form_for @room do |f|
            .row
              .col-md-12.space-1
                .form-group
                  %label{for: 'room_name'} お部屋の名前を記入して下さい
                  = f.text_field :name, class: 'form-control', id: 'room_name'
            .row
              .col-md-12.space-1
                .form-group
                  %label{for: 'room_detail'} お部屋の説明を記入して下さい
                  = f.text_area :detail, class: 'form-control', id: 'room_detail', rows: 3
            .row
              .col-md-12.space-1
                .form-group
                  %label{for: 'price'} 1泊当たりの金額を記入して下さい
                  = f.text_field :price, class: 'form-control', id: 'price'
            .row
              .col-md-6.space-1
                %h5 お部屋のタイプを選択して下さい
                = f.select :room_type, { 貸切: "reserved", 個室: "single", シェアルーム: "share"}, {}, {class: 'form-control'}
              .col-md-6.space-1
                %h5 宿泊可能人数を選択して下さい
                = f.select :capacity, { "1人": "1", "2人": "2", "3人": "3", "4人": "4", "5人以上": "5人以上"}, {}, {class: 'form-control'}
            .row
              .col-md-6.space-1
                %h5 寝室数を選択して下さい
                = f.select :bedroom_num, { 寝室1室: "1", 寝室2室: "2", 寝室3室: "3", 寝室4室以上: "4以上"}, {}, {class: 'form-control'}
              .col-md-6.space-1
                %h5 ベッド数を選択して下さい
                = f.select :bed_num, { ベッド1台: "1", ベッド2台: "2", ベッド3台: "3", ベッド4台以上: "4以上"}, {}, {class: 'form-control'}
            .row.space-1
              .col-md-12
                %h5 住所を記入して下さい
                = f.text_field :address, class: 'form-control', placeholder: "例: 東京都港区六本木６丁目１１−１", id: 'reg-address'
            .row.space-1
              .col-md-12
                = f.submit class: 'btn btn-danger btn-block', value: "登録"

= render 'rooms/footer'

:javascript
  function init() {
    var input = /** @type {!HTMLInputElement} */(
        document.getElementById('reg-address'));

    var autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.addListener('place_changed', function() {
      var place = autocomplete.getPlace();
      var lat = place.geometry.location.lat();
      var lng = place.geometry.location.lng();

      document.getElementById('lat').value = lat ;
      document.getElementById('lng').value = lng ;

      if (!place.geometry) {
        window.alert("Autocomplete's returned place contains no geometry");
        return;
      }

      var address = '';
      if (place.address_components) {
        address = [
          (place.address_components[0] && place.address_components[0].short_name || ''),
          (place.address_components[1] && place.address_components[1].short_name || ''),
          (place.address_components[2] && place.address_components[2].short_name || '')
        ].join(' ');
      }
    });
  }

%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAXbvOKObMqITgrrvsCSne77MDEA3T9f8o&libraries=places&callback=init"}

app/views/rooms/index.html.haml
= render 'header'
= render 'card_swipe'

.page-container
  = render 'search_form'

  .container-fluid
    .row.margin-48px
      .h4 お家
      - @rooms.each_with_index do |room, i|
        = link_to "/rooms/#{i+1}" do
          .col-md-4.margin-48px.color-484848
            = image_tag room.photos[0].image(:medium) if room.photos.length > 0
            %strong.text-left ¥
            %strong.text-lert= room.price
            %span.text-left
            %span.text-left= room.name

= render 'footer'

app/views/rooms/show.html.haml
= render 'header'

.clearfix

.cover-image
  - if @room.photos.length > 0
    = image_tag @room.photos[0].image(:original), class: 'cover-image'

.jumbotron.row-space-0{:style => "margin-top: -20px; background: none;"}
.container-fluid.container-listing-show
  .container
    .row
      -# - if @room.id == current_user.id
      = link_to edit_room_path(@room), class: 'col-md-12' do
        %button{class: 'btn btn-info'} 編集する
  .container
    .listing-summary.row-space-3.row-space-top-3
      .row
        .col-md-2.text-center.row-space-2
          = link_to '#host-profile' do
            = image_tag 'https://a1.muscache.com/im/users/35142183/profile_pic/1433607298/original.jpg?aki_policy=profile_x_medium', class: 'img-circle', style: "width: 90px"
          %h5 Michael
        .col-md-6
          .listing-title{:style => "font-size:24px;"}
            = @room.name
            %p
          .row.row-space-top-4
            .col-sm-3.col-xs-3.text-center
              %i.fa.fa-home.fa-3x
              %h5 まるまる貸切
            .col-sm-3.col-xs-3.text-center
              %i.fa.fa-users.fa-3x{"aria-hidden" => "true"}
              %h5 3人
            .col-sm-3.col-xs-3.text-center
              %i.fa.fa-university.fa-3x{"aria-hidden" => "true"}
              %h5 1寝室
            .col-sm-3.col-xs-3.text-center
              %i.fa.fa-bed.fa-3x{"aria-hidden" => "true"}
              %h5 1ベッド
        / 予約フォーム
        .col-md-4
          .panel.panel-default.panel-show
            .panel-heading
              %span{:style => "font-size:16px;"}
                = @room.price
                円（一晩あたり）
            .panel-body.panel-real
              = form_for [@room, @room.reservations.new] do |f|
                / これは、予約をするときに、一緒におくる、データです。
                -# = f.hidden_field :listing_id, value:
                -# = f.hidden_field :price_pernight, value:
                -# = f.hidden_field :total_price, id:'reservation_total_price'
                .row.row-space-2
                  .col-md-6
                    %label チェックイン
                    .date-range-picker
                      = f.text_field :start_date, name: 'startDate', class: 'form-control', placeholder: '開始'
                  .col-md-6
                    %label チェックアウト
                    = f.text_field :end_date, name: 'endDate',class: 'form-control', placeholder: '終了'
                  .col-md-12
                    %p
                    %p
                .actions.text-center
                  = f.submit "予約する", class: "btn btn-danger btn-lg btn-block"
%hr


.container-fluid.container-listing-show
  .container
    .listing-summary.row-space-3.row-space-top-3
      .row
        .col-md-9
          %h4.row-space-3 リスティングについて
          %p= @room.detail
          %hr

          .row
            .col-md-2
              %strong お部屋
            .col-md-5
              %span 収容人数：
              %strong 1
              %br
              %span 寝室：
              %strong 1
              %br
              %span チェックイン：
              %strong 15:00時以降ならいつでも
              %br
              %span 建物タイプ：
              %strong 一軒家
            .col-md-5
              %span バスルーム：
              %strong 1.5 (共同のバスルーム)
              %br
              %span ベッド：
              %strong 1
              %br
              %span チェックアウト：
              %strong 11:00
              %br
              %span 部屋タイプ：
              %strong 個室
      %hr
      -#   .col-md-3
      -# / レビュー
      -# .row
      -#   .col-md-9
      -#     %h4.row-space-3 レビュー
      -# .row
      -#   .col-md-9
      -#     %h4.row-space-3 ホストについて
      -#   .col-md-3
      .row
        .col-md-12
          %h4.row-space-3 アクセス
          #map
          :css
            #map{
                width: 100%;
                height: 650px;
            }
      / 近くのリスティング
      .row
        .col-md-12
          %h3.row-space-3 類似するリスティング
          - 3.times do |i|
            = link_to "/rooms/#{i+1}" do
              .col-md-4.margin-48px.color-484848
                = image_tag @rooms[i].photos[0].image(:original)
                %strong.text-left ¥
                %strong.text-lert= @rooms[i].price
                %span.text-left
                %span.text-left= @rooms[i].name

= render 'footer'

:javascript
  function initMap() {
    // Create the map.
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 14,
      center: {lat: #{@room.latitude}, lng: #{@room.longitude}},
      scrollwheel: false,
      mapTypeControl: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    // Add the circle for this city to the map.
    var cityCircle = new google.maps.Circle({
      strokeColor: '#00FFFF',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#00FFFF',
      fillOpacity: 0.35,
      map: map,
      center: {lat: #{@room.latitude}, lng: #{@room.longitude}},
      radius: 500
    });
    
  }
%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAXbvOKObMqITgrrvsCSne77MDEA3T9f8o&callback=initMap"}

app/views/users/show.html.haml
%p Show!